services:
  plugin-tests:
    container_name: ${TESTS_CONTAINER_NAME}
    build: .
    restart: on-failure
    env_file:
      - .env
    command: rake end2end_tests
    depends_on:
      mysqldb:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
        
  mysqldb:
    container_name: mysqldb
    build: ./examples/authors/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1"
      timeout: 20s
      retries: 10
      
  postgresdb:
    container_name: postgresdb
    build: ./examples/authors/postgresql
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: "pg_isready -d tests"
      timeout: 20s
      retries: 10
      